### ISSUE TITLE
Pull request on 2015-04-23-public-media-innovation.html, line 28 missing

### ISSUE THREAD

**Issue by buzzboldsteve** [jackbrighton/jackbrighton.github.io#1]
Hi Jack,
My branch shows line 28 still present, but for some reason the merge screen shows it missing. I didn't intend to cut this paragraph:

<p>In 1967 the first computer networks were just beginning to emerge from research at institutions like Stanford Research Center, Xerox PARC, and several other public universities who not coincidentally were also deeply involved in educational broadcasting. We were just beginning to imagine the possibilities for using computers and networks for purposes of education and public service. Whether or not LBJ’s remarks were based on an awareness of the specifics of this work, they foreshadow the media  world we live in today.</p>

**Comment by jackbrighton** [comment]
Hi Steven,

Thanks for participating! I'm not seeing a pull request though. Not sure what the deal is there...

**Comment by buzzboldsteve** [comment]
Apologies, thought I had sent the pull request post commit, but nope. Still seeing line 28 showing as removed in the diff. You're able to reject just that line in the merge, yes?

**Comment by jackbrighton** [comment]
I'll be honest: I'm very new to managing GitHub repositories but I figure to learn by doing. Your contribution helps me do that while building a better article for whoever is interested. Many thanks, and let's keep on rolling!
